name: flutter_ecom
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none"

# Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #provider: ^4.0.4
 # http: ^0.12.1
  #cupertino_icons: ^1.0.2
  carousel_pro: ^1.0.0
  currency_text_input_formatter: ^2.0.1
  firebase_auth: ^1.1.1
  cloud_firestore: ^1.0.6
  google_sign_in: ^5.0.2
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.4
  cached_network_image: ^3.0.0
  images_picker: ^1.2.0
  intl: ^0.17.0
  firebase_database: ^6.1.2
  flutter_typeahead: ^3.1.1
  transparent_image: ^2.0.0
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
    #cloud_firestore: ^1.0.4
    #cupertino_icons: ^1.0.2
  dio: ^4.0.0
    #firebase_auth: ^1.0.2
  #firebase_core: ^1.0.3
  firebase_core: ^1.0.0
  firebase_messaging: ^10.0.0
    #flutter_spinkit: ^5.0.0
  get: ^4.1.3
  logger: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  stripe_payment: ^1.1.0
  uuid: ^3.0.4
  timeago: ^3.0.2

    #js: ^0.6.2
    #web_socket_channel: ^1.1.0
    #firebase: ^5.0.0
    #firebase_core : ^1.0.4
    # firebase_auth_web: ^1.0.6
    #firebase_auth_web: ^1.0.7
    #http_parser: ^4.0.0
    #http: ^0.11.3
    #http ^0.11.3


    # firebase_core:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/A4books.png
    - images/bagg.jpeg
    - images/BasmatiRice.jpeg
    - images/bathingsoap.jpeg
    - images/bathingsoapp.jpeg
    - images/bic.jpeg
    - images/bicc.png
    - images/bicproduct.jpeg
    - images/books.jpeg
    - images/breakfastcereal.jpeg
    - images/brookside.jpeg
    - images/brooksidee.jpeg
    - images/Brooksidemilkd.jpeg
    - images/c1.jpg
    - images/carrt.png
    - images/cart2.jpg
    - images/cart3.jpg
    - images/cart5.jpg
    - images/cats/accessories.png
    - images/cats/dress.png
    - images/cats/formal.png
    - images/cats/informal.png
    - images/cats/jeans.png
    - images/cats/shoe.png
    - images/cats/tshirt.png
    - images/cereal.jpeg
    - images/cocacola.png
    - images/cocacola2.jpeg
    - images/coffee.png
    - images/coke2.jpeg
    - images/cokee.jpeg
    - images/Dairy.png
    - images/Downy.jpeg
    - images/drinks.jpeg
    - images/drinks22.jpeg
    - images/drinksa.png
    - images/drinkss.jpg
    - images/google.png
    - images/handsanitizer.jpeg
    - images/laundry.png
    - images/lays.png
    - images/logo.png
    - images/m1.jpeg
    - images/m2.jpg
    - images/maccoffe.jpg
    - images/maxfresh.jpeg
    - images/milk.png
    - images/milkk.png
    - images/penns.jpeg
    - images/pens.png
    - images/potatochips.png
    - images/products/blazer1.jpeg
    - images/products/blazer2.jpeg
    - images/products/dress1.jpeg
    - images/products/dress2.jpeg
    - images/products/hills1.jpeg
    - images/products/hills2.jpeg
    - images/products/pants1.jpg
    - images/products/pants2.jpeg
    - images/products/potato.jpeg
    - images/products/potatolays.jpeg
    - images/products/shoe1.jpg
    - images/products/skt1.jpeg
    - images/products/skt2.jpeg
    - images/Rice.jpeg
    - images/shoocart.png
    - images/Soap.jpeg
    - images/softdrinks.jpeg
    - images/suagar.jpg
    - images/sun.jpeg
    - images/sunlight.jpg
    - images/ToothPaste.png
    - images/ueablogo.png
    - images/urban.jpeg
    - images/urbanbites.jpg
    - images/vasline.jpeg
    - images/Vasline.jpeg
    - images/vegetables.jpeg
    - images/w1.jpeg
    - images/w3.jpeg
    - images/w4.jpeg
    - images/weetabix.jpeg
    - images/Zero.jpeg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
